parameters:
  - name: dependsOnEnv
    type: string
    default: ''
  - name: condition
    type: string
    default: 'always()'

stages:
  - stage: Build
    ${{ if eq(parameters.dependsOnEnv, '') }}:
      dependsOn: []
    ${{ if ne(parameters.dependsOnEnv, '') }}:
      dependsOn: '${{parameters.dependsOnEnv}}'
    condition: ${{ parameters.condition }}
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - template: ../variables/variables-common.yaml
    jobs:
      - job: BasicValidation
        steps:
          - template: ../steps/tf-install.yaml
          - template: ../steps/tf-init.yaml
            parameters:
              useBackend: false
          - task: TerraformCLI@0
            displayName: Validate Terraform
            inputs:
              command: 'validate'
              commandOptions: '-no-color'
          - script: terraform fmt -check=true
            displayName: Check Formatting