parameters:
  - name: env
    type: string
    default: 'sbox'
#TODO: only run these if not prod or is prod and master branch
stages:
  - stage: Wait${{parameters.env}}
    displayName: '${{parameters.env}} Waiting for Approval'
    condition: and(ne(parameters.env,'sbox'))
    dependsOn: Plan${{parameters.env}}
    jobs:
      - job: waitForValidation
        displayName: '${{parameters.env}} Wait for external validation'
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
            instructions: 'Please validate the Terraform Plan for PROD environment to resume'
            onTimeout: 'reject'

  - stage: Apply${{parameters.env}}
    displayName: 'Apply to ${{parameters.env}}'
    ${{ if eq(parameters.env, 'sbox') }}:
      dependsOn: Plan${{parameters.env}}
    ${{ if ne(parameters.env, 'sbox') }}:
      dependsOn: Wait${{parameters.env}}
    variables:
      - template: ../variables/variables-common.yaml
      - ${{ if ne(parameters.env, 'prod') }}:
        - template: ../variables/variables-${{parameters.env}}.yaml
        - group: cvp-${{parameters.env}}
      - ${{ if and(contains(variables['Build.SourceBranch'], 'refs/heads/master'), eq(parameters.env, 'prod')) }}:
        # Production (prod)
        - template: ../variables/variables-prod.yaml
        - group: cvp-prod
    jobs:
      - job: ApplytoEnv
        displayName: 'Apply to ${{parameters.env}}'
        steps:
          - template: ../steps/tf-apply.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              env: $(env)

          - template: ../steps/az-dynatrace.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              env: $(env)
              location: $(location)
              product: $(product)
