parameters:
  - name: env
    type: string
    default: 'sbox'
  - name: dependsOnEnv
    type: string
    default: ''

stages:
  - stage: 'Plan${{parameters.env}}'
    displayName: 'Plan ${{parameters.env}}'
    ${{ if eq(parameters.dependsOnEnv, '') }}:
      dependsOn: Build
    ${{ if ne(parameters.dependsOnEnv, '') }}:
      dependsOn: 'Test${{parameters.dependsOnEnv}}'
    variables:
      - template: ../variables/variables-common.yaml
      - template: ../variables/variables-${{parameters.env}}.yaml
      - group: cvp-${{parameters.env}}
    jobs:
      - template: ../template/validSslCertificate.yaml
        parameters:
          subscriptionName: ${{variables.subscriptionName}}
          resourceGroupName: ${{variables.product}}-recordings-${{parameters.env}}-rg
          nsgName: ${{variables.product}}-recordings-${{parameters.env}}-sg
          virtualMachines:
            - vms:
              vmName: ${{variables.product}}-recordings-${{parameters.env}}-vm1
              publicIpName: ${{variables.product}}-recordings-${{parameters.env}}-pipvm1
            - vms:
              vmName: ${{variables.product}}-recordings-${{parameters.env}}-vm2
              publicIpName: ${{variables.product}}-recordings-${{parameters.env}}-pipvm2
      - job: PlanToEnv${{parameters.env}}
        displayName: 'Plan to ${{parameters.env}}'
        steps:

          - template: ../steps/tf-init.yaml
            parameters:
              subscriptionName: ${{variables.subscriptionName}}
              env: ${{variables.env}}
              location: ${{variables.location}}
              locationEng: ${{variables.locationEng}}
              product: ${{variables.product}}
              useBackend: true

          - template: ../steps/tf-plan.yaml
            parameters:
              subscriptionName: ${{variables.subscriptionName}}
              env: ${{variables.env}}
              certName: ${{variables.certName}}
              location: ${{variables.location}}
              product: ${{variables.product}}
              builtFrom: $(Build.Repository.Name)
              # Manually passed in for use in scripts where resources are tagged
              businessArea: ${{variables.businessArea}}
              application: ${{variables.application}}