trigger:
  - master
pr:
  - master

schedules:
  - cron: "0 1 * * 1"
    displayName: Weekly Run
    branches:
      include:
      - master
    always: false

parameters:
  - name: envs
    displayName: Environments
    type: object
    values: []
    default: ['sbox','stg','prod']

stages:
  - templates: pipeline/stages/build.yaml

  - ${{each env in parameters.envs}}:
    - templates: pipeline/stages/plan.yaml
      parameters:
        env: ${{env}}
        ${{ if eq(variables["env"], 'sbox') }}:
          dependsOnEnv: ''
        ${{ if eq(variables["env"], 'stg') }}:
          dependsOnEnv: ${{sbox}}
        ${{ if eq(variables["env"], 'prod') }}:
          dependsOnEnv: ${{stg}}

  - ${{each env in parameters.envs}}:
    - templates: pipeline/stages/deploy.yaml
      parameters:
        env: ${{env}}